library(Tetmer)

makeTestSpectrum <- function() {
  mult <- 1:250
  # Smooth positive counts to keep plotting and y-limit defaults stable.
  count <- as.numeric(round(100 + 100000 * exp(-((mult - 60)^2) / (2 * 20^2))))
  methods::new("spectrum",
    name = "synthetic",
    data = data.frame(mult = mult, count = count),
    k = 21,
    fits = list()
  )
}

makeTestFit <- function(model, version = as.character(utils::packageVersion("Tetmer"))) {
  par <- c(cov = 30, vf = 1.5, theta = 0.04, haplSize = 200)
  if (model %in% c("traab", "tal", "tse")) {
    par <- c(par, diverg = 30)
  }
  if (model == "tse") {
    par <- c(par, pallo = 0.6)
  }

  methods::new("tetmerFit",
    model = model,
    par = par,
    ranges = list(),
    xrange = c(10, 80),
    convergence = 0,
    value = 1,
    k = 21,
    version = version
  )
}

withPngDevice <- function(code) {
  tf <- tempfile(fileext = ".png")
  grDevices::png(tf)
  on.exit({
    grDevices::dev.off()
    unlink(tf)
  }, add = TRUE)
  force(code)
}

test_that("plot.spectrum overlays fits for all supported models", {
  models <- c("d", "traaa", "traab", "tau", "tal", "tse")

  for (model in models) {
    spec <- makeTestSpectrum()
    fit <- makeTestFit(model)
    spec <- addFit(spec, fit)

    expect_message(
      expect_no_warning(withPngDevice(plot(spec, fitIndex = 1))),
      "showing fit index 1"
    )
  }
})

test_that("plot.spectrum warns when plotting fit from different Tetmer version", {
  spec <- makeTestSpectrum()
  spec <- addFit(spec, makeTestFit("d", version = "0.0.0"))

  expect_message(
    suppressWarnings(withPngDevice(plot(spec, fitIndex = 1))),
    "showing fit index 1"
  )
  expect_warning(
    withPngDevice(plot(spec, fitIndex = 1)),
    "generated by Tetmer v0.0.0"
  )
})

test_that("plot.spectrum does not warn on version when fit uses current Tetmer version", {
  spec <- makeTestSpectrum()
  spec <- addFit(spec, makeTestFit("d"))

  expect_message(
    expect_no_warning(withPngDevice(plot(spec, fitIndex = 1))),
    "showing fit index 1"
  )
})

test_that("plot.spectrum fitIndex = NA suppresses fit overlay and version warning", {
  spec <- makeTestSpectrum()
  spec <- addFit(spec, makeTestFit("d", version = "0.0.0"))

  expect_no_message(withPngDevice(plot(spec, fitIndex = NA)))
  expect_no_warning(withPngDevice(plot(spec, fitIndex = NA)))
})