library(Tetmer)

makeTestSpectrum <- function() {
  mult <- 1:250
  # Smooth positive counts to keep plotting and y-limit defaults stable.
  count <- as.numeric(round(100 + 100000 * exp(-((mult - 60)^2) / (2 * 20^2))))
  methods::new("spectrum",
    name = "synthetic",
    data = data.frame(mult = mult, count = count),
    k = 21,
    fits = list()
  )
}

makeTestFit <- function(model,
                        version = as.character(utils::packageVersion("Tetmer")),
                        fitType = "auto") {
  par <- c(cov = 30, vf = 1.5, theta = 0.04, haplSize = 200)
  if (model %in% c("traab", "tal", "tse")) {
    par <- c(par, diverg = 30)
  }
  if (model == "tse") {
    par <- c(par, pallo = 0.6)
  }

  methods::new("tetmerFit",
    fitType = fitType,
    model = model,
    par = par,
    ranges = list(),
    xrange = if (identical(fitType, "manual")) c(1, 80) else c(10, 80),
    convergence = 0,
    value = 1,
    k = 21,
    version = version
  )
}

withPngDevice <- function(code) {
  tf <- tempfile(fileext = ".png")
  grDevices::png(tf)
  on.exit({
    grDevices::dev.off()
    unlink(tf)
  }, add = TRUE)
  force(code)
}

test_that("plot.spectrum overlays fits for all supported models", {
  models <- c("d", "traaa", "traab", "tau", "tal", "tse")

  for (model in models) {
    spec <- makeTestSpectrum()
    fit <- makeTestFit(model)
    spec <- addFit(spec, fit)

    expect_message(
      expect_no_warning(withPngDevice(plot(spec, fitIndex = 1))),
      "showing fit index 1"
    )
  }
})

test_that("plot.spectrum warns when plotting fit from different Tetmer version", {
  spec <- makeTestSpectrum()
  spec <- addFit(spec, makeTestFit("d", version = "0.0.0"))

  expect_message(
    suppressWarnings(withPngDevice(plot(spec, fitIndex = 1))),
    "showing fit index 1"
  )
  expect_warning(
    withPngDevice(plot(spec, fitIndex = 1)),
    "generated by Tetmer v0.0.0"
  )
})

test_that("plot.spectrum does not warn on version when fit uses current Tetmer version", {
  spec <- makeTestSpectrum()
  spec <- addFit(spec, makeTestFit("d"))

  expect_message(
    expect_no_warning(withPngDevice(plot(spec, fitIndex = 1))),
    "showing fit index 1"
  )
})

test_that("plot.spectrum fitIndex = NA suppresses fit overlay and version warning", {
  spec <- makeTestSpectrum()
  spec <- addFit(spec, makeTestFit("d", version = "0.0.0"))

  expect_no_message(withPngDevice(plot(spec, fitIndex = NA)))
  expect_no_warning(withPngDevice(plot(spec, fitIndex = NA)))
})

test_that("plot.spectrum uses fitted y maximum for manual fits", {
  spec <- makeTestSpectrum()
  fit <- makeTestFit("d", fitType = "manual")
  spec@data$count[fit@xrange[1]] <- 1e8
  spec <- addFit(spec, fit)

  expectedYMax <- 1.1 * max(expectedSpectrum(fit, xrange = c(5, 80))@data$count)

  usr <- NULL
  expect_message(
    usr <- withPngDevice({
      plot(spec, fitIndex = 1, xaxs = "i", yaxs = "i")
      graphics::par("usr")
    }),
    "showing fit index 1"
  )

  expect_equal(usr[1], 5)
  expect_equal(usr[3], 0)
  expect_equal(usr[4], expectedYMax, tolerance = 1e-6)
})

test_that("plot.spectrum keeps data y maximum for automatic fits", {
  spec <- makeTestSpectrum()
  fit <- makeTestFit("d")
  spec@data$count[fit@xrange[1]] <- 1e8
  spec <- addFit(spec, fit)

  usr <- NULL
  expect_message(
    usr <- withPngDevice({
      plot(spec, fitIndex = 1, yaxs = "i")
      graphics::par("usr")
    }),
    "showing fit index 1"
  )

  expect_equal(usr[4], max(spec@data$count[fit@xrange[1]:fit@xrange[2]]))
})

test_that("plot.spectrum respects explicit ylim for manual fits", {
  spec <- makeTestSpectrum()
  fit <- makeTestFit("d", fitType = "manual")
  spec@data$count[fit@xrange[1]] <- 1e8
  spec <- addFit(spec, fit)

  usr <- NULL
  expect_message(
    usr <- withPngDevice({
      plot(spec, fitIndex = 1, ylim = c(0, 123), yaxs = "i")
      graphics::par("usr")
    }),
    "showing fit index 1"
  )

  expect_equal(usr[3:4], c(0, 123))
})

test_that("plot.spectrum overlay uses diagnostic x-range for manual fits", {
  spec <- makeTestSpectrum()
  fit <- makeTestFit("d", fitType = "manual")
  spec@data$count[fit@xrange[1]] <- 1e8
  spec <- addFit(spec, fit)

  diagnosticRange <- c(5, fit@xrange[2])
  expectedYMax <- max(spec@data$count[diagnosticRange[1]:diagnosticRange[2]])

  usr <- NULL
  expect_message(
    usr <- withPngDevice({
      plot(spec, fitIndex = 1, residuals = "overlay", xaxs = "i", yaxs = "i")
      graphics::par("usr")
    }),
    "showing fit index 1"
  )

  expect_equal(usr[1], diagnosticRange[1])
  expect_equal(usr[4], expectedYMax, tolerance = 1e-6)
  expect_lt(usr[4], spec@data$count[fit@xrange[1]])
})

test_that("plot.spectrum manualXRange overrides manual diagnostic range", {
  spec <- makeTestSpectrum()
  fit <- makeTestFit("d", fitType = "manual")
  spec@data$count[fit@xrange[1]] <- 1e8
  spec <- addFit(spec, fit)

  manualXRange <- c(20, 70)
  expectedYMax <- max(spec@data$count[manualXRange[1]:manualXRange[2]])

  usr <- NULL
  expect_message(
    usr <- withPngDevice({
      plot(spec, fitIndex = 1, residuals = "overlay",
           manualXRange = manualXRange, xaxs = "i", yaxs = "i")
      graphics::par("usr")
    }),
    "showing fit index 1"
  )

  expect_equal(usr[1:2], c(manualXRange[1], manualXRange[2] * 1.1))
  expect_equal(usr[4], expectedYMax, tolerance = 1e-6)
})

test_that("plot.spectrum manualXRange applies to residual-only manual plots", {
  spec <- makeTestSpectrum()
  fit <- makeTestFit("d", fitType = "manual")
  spec@data$count[fit@xrange[1]] <- 1e8
  spec <- addFit(spec, fit)

  manualXRange <- c(20, 70)

  usr <- NULL
  expect_message(
    usr <- withPngDevice({
      plot(spec, fitIndex = 1, residuals = TRUE,
           manualXRange = manualXRange, xaxs = "i")
      graphics::par("usr")
    }),
    "showing fit index 1"
  )

  expect_equal(usr[1:2], c(manualXRange[1], manualXRange[2] * 1.1))
})

test_that("plot.spectrum ignores manualXRange for automatic fits", {
  spec <- makeTestSpectrum()
  fit <- makeTestFit("d")
  spec@data$count[fit@xrange[1]] <- 1e8
  spec <- addFit(spec, fit)

  usr <- NULL
  expect_message(
    usr <- withPngDevice({
      plot(spec, fitIndex = 1, residuals = "overlay",
           manualXRange = c(20, 70), xaxs = "i", yaxs = "i")
      graphics::par("usr")
    }),
    "showing fit index 1"
  )

  expect_equal(usr[1:2], c(0, fit@xrange[2] * 1.1))
  expect_equal(usr[4], max(spec@data$count[fit@xrange[1]:fit@xrange[2]]))
})

test_that("plot.spectrum accepts fit and residual colour parameters", {
  spec <- makeTestSpectrum()
  spec <- addFit(spec, makeTestFit("d", fitType = "manual"))

  expect_message(
    expect_no_error(withPngDevice(
      plot(spec, fitIndex = 1, residuals = "overlay",
           col = "grey30", colFit = 2, colResid = 3)
    )),
    "showing fit index 1"
  )
  expect_message(
    expect_no_error(withPngDevice(
      plot(spec, fitIndex = 1, residuals = TRUE,
           col = "grey30", colResid = "blue")
    )),
    "showing fit index 1"
  )
})
